// Auto-generated by scripts/generate-svm-event-manifest.ts — do not edit manually

use borsh::BorshSerialize;
use super::emit_program_data;

/// AscendingConsignment:AscendingTermsSnapshotted
pub fn emit_ascending_consignment_ascending_terms_snapshotted(tokenId: [u8; 32], duration: u64, extensionWindow: u64, protectionWindow: u64, abandonmentWindow: u64, minIncrementBps: u16, reserve: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    duration.serialize(&mut body).expect("event field serialize");
    extensionWindow.serialize(&mut body).expect("event field serialize");
    protectionWindow.serialize(&mut body).expect("event field serialize");
    abandonmentWindow.serialize(&mut body).expect("event field serialize");
    minIncrementBps.serialize(&mut body).expect("event field serialize");
    reserve.serialize(&mut body).expect("event field serialize");
    emit_program_data("AscendingTermsSnapshotted", &body);
}

/// AscendingConsignment:AuctionRulesSet
pub fn emit_ascending_consignment_auction_rules_set(minDuration: u64, maxDuration: u64, extensionWindow: u64, minIncrementBps: u16, minProtectionWindow: u64, maxProtectionWindow: u64, abandonmentWindow: u64, challengeBond: u64) {
    let mut body = Vec::new();
    minDuration.serialize(&mut body).expect("event field serialize");
    maxDuration.serialize(&mut body).expect("event field serialize");
    extensionWindow.serialize(&mut body).expect("event field serialize");
    minIncrementBps.serialize(&mut body).expect("event field serialize");
    minProtectionWindow.serialize(&mut body).expect("event field serialize");
    maxProtectionWindow.serialize(&mut body).expect("event field serialize");
    abandonmentWindow.serialize(&mut body).expect("event field serialize");
    challengeBond.serialize(&mut body).expect("event field serialize");
    emit_program_data("AuctionRulesSet", &body);
}

/// AscendingConsignment:BidPlaced
pub fn emit_ascending_consignment_bid_placed(tokenId: [u8; 32], bidder: [u8; 32], amount: u64, endsAt: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    bidder.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    endsAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("BidPlaced", &body);
}

/// AscendingConsignment:BidRefunded
pub fn emit_ascending_consignment_bid_refunded(tokenId: [u8; 32], bidder: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    bidder.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("BidRefunded", &body);
}

/// AscendingConsignment:ChallengeConcluded
pub fn emit_ascending_consignment_challenge_concluded(subjectId: [u8; 32], challenger: [u8; 32], bondRecipient: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    bondRecipient.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeConcluded", &body);
}

/// AscendingConsignment:ChallengeJudged
pub fn emit_ascending_consignment_challenge_judged(subjectId: [u8; 32], challenger: [u8; 32], judge: [u8; 32], outcome: u8, bondRecipient: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    judge.serialize(&mut body).expect("event field serialize");
    outcome.serialize(&mut body).expect("event field serialize");
    bondRecipient.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeJudged", &body);
}

/// AscendingConsignment:ChallengeOpened
pub fn emit_ascending_consignment_challenge_opened(subjectId: [u8; 32], challenger: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeOpened", &body);
}

/// AscendingConsignment:ChallengeWithdrawn
pub fn emit_ascending_consignment_challenge_withdrawn(subjectId: [u8; 32], challenger: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeWithdrawn", &body);
}

/// AscendingConsignment:ClaimRecorded
pub fn emit_ascending_consignment_claim_recorded(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimRecorded", &body);
}

/// AscendingConsignment:ClaimWithdrawn
pub fn emit_ascending_consignment_claim_withdrawn(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimWithdrawn", &body);
}

/// AscendingConsignment:ConsignmentClosed
pub fn emit_ascending_consignment_consignment_closed(tokenId: [u8; 32], reason: u8) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    reason.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentClosed", &body);
}

/// AscendingConsignment:ConsignmentCommissionLowered
pub fn emit_ascending_consignment_consignment_commission_lowered(tokenId: [u8; 32], newBps: u16) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    newBps.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentCommissionLowered", &body);
}

/// AscendingConsignment:ConsignmentFloorLowered
pub fn emit_ascending_consignment_consignment_floor_lowered(tokenId: [u8; 32], newFloor: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    newFloor.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentFloorLowered", &body);
}

/// AscendingConsignment:ConsignmentOpened
pub fn emit_ascending_consignment_consignment_opened(tokenId: [u8; 32], seller: [u8; 32], agent: [u8; 32], asset: [u8; 32], denominationKind: u8, currencyCode: [u8; 32], floor: u64, compensationForm: u8, commissionBps: u16, price: u64, platformFeeBps: u16, openedAt: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    seller.serialize(&mut body).expect("event field serialize");
    agent.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    denominationKind.serialize(&mut body).expect("event field serialize");
    currencyCode.serialize(&mut body).expect("event field serialize");
    floor.serialize(&mut body).expect("event field serialize");
    compensationForm.serialize(&mut body).expect("event field serialize");
    commissionBps.serialize(&mut body).expect("event field serialize");
    price.serialize(&mut body).expect("event field serialize");
    platformFeeBps.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentOpened", &body);
}

/// AscendingConsignment:ConsignmentPriceSet
pub fn emit_ascending_consignment_consignment_price_set(tokenId: [u8; 32], setter: [u8; 32], newPrice: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    setter.serialize(&mut body).expect("event field serialize");
    newPrice.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentPriceSet", &body);
}

/// AscendingConsignment:ConsignmentSplitPaid
pub fn emit_ascending_consignment_consignment_split_paid(tokenId: [u8; 32], asset: [u8; 32], ownerRecipient: [u8; 32], ownerAmount: u64, agentRecipient: [u8; 32], agentAmount: u64, platformRecipient: [u8; 32], platformAmount: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    ownerRecipient.serialize(&mut body).expect("event field serialize");
    ownerAmount.serialize(&mut body).expect("event field serialize");
    agentRecipient.serialize(&mut body).expect("event field serialize");
    agentAmount.serialize(&mut body).expect("event field serialize");
    platformRecipient.serialize(&mut body).expect("event field serialize");
    platformAmount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentSplitPaid", &body);
}

/// AscendingConsignment:FundsReleased
pub fn emit_ascending_consignment_funds_released(tokenId: [u8; 32], buyer: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    emit_program_data("FundsReleased", &body);
}

/// AscendingConsignment:GuardianSet
pub fn emit_ascending_consignment_guardian_set(previous: [u8; 32], current: [u8; 32]) {
    let mut body = Vec::new();
    previous.serialize(&mut body).expect("event field serialize");
    current.serialize(&mut body).expect("event field serialize");
    emit_program_data("GuardianSet", &body);
}

/// AscendingConsignment:MandateGranted
pub fn emit_ascending_consignment_mandate_granted(tokenId: [u8; 32], owner: [u8; 32], agent: [u8; 32], expiry: u64, asset: [u8; 32], denominationKind: u8, currencyCode: [u8; 32], floor: u64, compensationForm: u8, commissionBps: u16) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    owner.serialize(&mut body).expect("event field serialize");
    agent.serialize(&mut body).expect("event field serialize");
    expiry.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    denominationKind.serialize(&mut body).expect("event field serialize");
    currencyCode.serialize(&mut body).expect("event field serialize");
    floor.serialize(&mut body).expect("event field serialize");
    compensationForm.serialize(&mut body).expect("event field serialize");
    commissionBps.serialize(&mut body).expect("event field serialize");
    emit_program_data("MandateGranted", &body);
}

/// AscendingConsignment:MandateRevoked
pub fn emit_ascending_consignment_mandate_revoked(tokenId: [u8; 32], owner: [u8; 32], priorAgent: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    owner.serialize(&mut body).expect("event field serialize");
    priorAgent.serialize(&mut body).expect("event field serialize");
    emit_program_data("MandateRevoked", &body);
}

/// AscendingConsignment:Paused
pub fn emit_ascending_consignment_paused(account: [u8; 32]) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    emit_program_data("Paused", &body);
}

/// AscendingConsignment:PaymentTokenApproved
pub fn emit_ascending_consignment_payment_token_approved(token: [u8; 32]) {
    let mut body = Vec::new();
    token.serialize(&mut body).expect("event field serialize");
    emit_program_data("PaymentTokenApproved", &body);
}

/// AscendingConsignment:PaymentTokenRevoked
pub fn emit_ascending_consignment_payment_token_revoked(token: [u8; 32]) {
    let mut body = Vec::new();
    token.serialize(&mut body).expect("event field serialize");
    emit_program_data("PaymentTokenRevoked", &body);
}

/// AscendingConsignment:RecallRequested
pub fn emit_ascending_consignment_recall_requested(tokenId: [u8; 32], seller: [u8; 32], requestedAt: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    seller.serialize(&mut body).expect("event field serialize");
    requestedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("RecallRequested", &body);
}

/// AscendingConsignment:ReceiptConfirmed
pub fn emit_ascending_consignment_receipt_confirmed(tokenId: [u8; 32], buyer: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    emit_program_data("ReceiptConfirmed", &body);
}

/// AscendingConsignment:ReversalAbandoned
pub fn emit_ascending_consignment_reversal_abandoned(tokenId: [u8; 32], buyer: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    emit_program_data("ReversalAbandoned", &body);
}

/// AscendingConsignment:ReversalCompleted
pub fn emit_ascending_consignment_reversal_completed(tokenId: [u8; 32], buyer: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    emit_program_data("ReversalCompleted", &body);
}

/// AscendingConsignment:ReversalStarted
pub fn emit_ascending_consignment_reversal_started(tokenId: [u8; 32], buyer: [u8; 32], abandonmentDeadline: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    abandonmentDeadline.serialize(&mut body).expect("event field serialize");
    emit_program_data("ReversalStarted", &body);
}

/// AscendingConsignment:Settled
pub fn emit_ascending_consignment_settled(tokenId: [u8; 32], buyer: [u8; 32], gross: u64, protectionEndsAt: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    gross.serialize(&mut body).expect("event field serialize");
    protectionEndsAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("Settled", &body);
}

/// AscendingConsignment:Unpaused
pub fn emit_ascending_consignment_unpaused(account: [u8; 32]) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    emit_program_data("Unpaused", &body);
}

/// FixedPriceConsignment:Bought
pub fn emit_fixed_price_consignment_bought(tokenId: [u8; 32], buyer: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("Bought", &body);
}

/// FixedPriceConsignment:ClaimRecorded
pub fn emit_fixed_price_consignment_claim_recorded(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimRecorded", &body);
}

/// FixedPriceConsignment:ClaimWithdrawn
pub fn emit_fixed_price_consignment_claim_withdrawn(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimWithdrawn", &body);
}

/// FixedPriceConsignment:ConsignmentClosed
pub fn emit_fixed_price_consignment_consignment_closed(tokenId: [u8; 32], reason: u8) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    reason.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentClosed", &body);
}

/// FixedPriceConsignment:ConsignmentCommissionLowered
pub fn emit_fixed_price_consignment_consignment_commission_lowered(tokenId: [u8; 32], newBps: u16) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    newBps.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentCommissionLowered", &body);
}

/// FixedPriceConsignment:ConsignmentFloorLowered
pub fn emit_fixed_price_consignment_consignment_floor_lowered(tokenId: [u8; 32], newFloor: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    newFloor.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentFloorLowered", &body);
}

/// FixedPriceConsignment:ConsignmentOpened
pub fn emit_fixed_price_consignment_consignment_opened(tokenId: [u8; 32], seller: [u8; 32], agent: [u8; 32], asset: [u8; 32], denominationKind: u8, currencyCode: [u8; 32], floor: u64, compensationForm: u8, commissionBps: u16, price: u64, platformFeeBps: u16, openedAt: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    seller.serialize(&mut body).expect("event field serialize");
    agent.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    denominationKind.serialize(&mut body).expect("event field serialize");
    currencyCode.serialize(&mut body).expect("event field serialize");
    floor.serialize(&mut body).expect("event field serialize");
    compensationForm.serialize(&mut body).expect("event field serialize");
    commissionBps.serialize(&mut body).expect("event field serialize");
    price.serialize(&mut body).expect("event field serialize");
    platformFeeBps.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentOpened", &body);
}

/// FixedPriceConsignment:ConsignmentPriceSet
pub fn emit_fixed_price_consignment_consignment_price_set(tokenId: [u8; 32], setter: [u8; 32], newPrice: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    setter.serialize(&mut body).expect("event field serialize");
    newPrice.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentPriceSet", &body);
}

/// FixedPriceConsignment:ConsignmentSplitPaid
pub fn emit_fixed_price_consignment_consignment_split_paid(tokenId: [u8; 32], asset: [u8; 32], ownerRecipient: [u8; 32], ownerAmount: u64, agentRecipient: [u8; 32], agentAmount: u64, platformRecipient: [u8; 32], platformAmount: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    ownerRecipient.serialize(&mut body).expect("event field serialize");
    ownerAmount.serialize(&mut body).expect("event field serialize");
    agentRecipient.serialize(&mut body).expect("event field serialize");
    agentAmount.serialize(&mut body).expect("event field serialize");
    platformRecipient.serialize(&mut body).expect("event field serialize");
    platformAmount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ConsignmentSplitPaid", &body);
}

/// FixedPriceConsignment:CurrencyFeedSet
pub fn emit_fixed_price_consignment_currency_feed_set(currencyCode: [u8; 32], feed: [u8; 32], stalenessTolerance: u32) {
    let mut body = Vec::new();
    currencyCode.serialize(&mut body).expect("event field serialize");
    feed.serialize(&mut body).expect("event field serialize");
    stalenessTolerance.serialize(&mut body).expect("event field serialize");
    emit_program_data("CurrencyFeedSet", &body);
}

/// FixedPriceConsignment:ExternalPaymentConfirmed
pub fn emit_fixed_price_consignment_external_payment_confirmed(tokenId: [u8; 32], buyer: [u8; 32], confirmer: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    buyer.serialize(&mut body).expect("event field serialize");
    confirmer.serialize(&mut body).expect("event field serialize");
    emit_program_data("ExternalPaymentConfirmed", &body);
}

/// FixedPriceConsignment:GuardianSet
pub fn emit_fixed_price_consignment_guardian_set(previous: [u8; 32], current: [u8; 32]) {
    let mut body = Vec::new();
    previous.serialize(&mut body).expect("event field serialize");
    current.serialize(&mut body).expect("event field serialize");
    emit_program_data("GuardianSet", &body);
}

/// FixedPriceConsignment:MandateGranted
pub fn emit_fixed_price_consignment_mandate_granted(tokenId: [u8; 32], owner: [u8; 32], agent: [u8; 32], expiry: u64, asset: [u8; 32], denominationKind: u8, currencyCode: [u8; 32], floor: u64, compensationForm: u8, commissionBps: u16) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    owner.serialize(&mut body).expect("event field serialize");
    agent.serialize(&mut body).expect("event field serialize");
    expiry.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    denominationKind.serialize(&mut body).expect("event field serialize");
    currencyCode.serialize(&mut body).expect("event field serialize");
    floor.serialize(&mut body).expect("event field serialize");
    compensationForm.serialize(&mut body).expect("event field serialize");
    commissionBps.serialize(&mut body).expect("event field serialize");
    emit_program_data("MandateGranted", &body);
}

/// FixedPriceConsignment:MandateRevoked
pub fn emit_fixed_price_consignment_mandate_revoked(tokenId: [u8; 32], owner: [u8; 32], priorAgent: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    owner.serialize(&mut body).expect("event field serialize");
    priorAgent.serialize(&mut body).expect("event field serialize");
    emit_program_data("MandateRevoked", &body);
}

/// FixedPriceConsignment:NativeUsdStalenessToleranceSet
pub fn emit_fixed_price_consignment_native_usd_staleness_tolerance_set(previous: u32, current: u32) {
    let mut body = Vec::new();
    previous.serialize(&mut body).expect("event field serialize");
    current.serialize(&mut body).expect("event field serialize");
    emit_program_data("NativeUsdStalenessToleranceSet", &body);
}

/// FixedPriceConsignment:Paused
pub fn emit_fixed_price_consignment_paused(account: [u8; 32]) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    emit_program_data("Paused", &body);
}

/// FixedPriceConsignment:PaymentTokenApproved
pub fn emit_fixed_price_consignment_payment_token_approved(token: [u8; 32], feed: [u8; 32], decimals: u8, stalenessTolerance: u32) {
    let mut body = Vec::new();
    token.serialize(&mut body).expect("event field serialize");
    feed.serialize(&mut body).expect("event field serialize");
    decimals.serialize(&mut body).expect("event field serialize");
    stalenessTolerance.serialize(&mut body).expect("event field serialize");
    emit_program_data("PaymentTokenApproved", &body);
}

/// FixedPriceConsignment:PaymentTokenRevoked
pub fn emit_fixed_price_consignment_payment_token_revoked(token: [u8; 32]) {
    let mut body = Vec::new();
    token.serialize(&mut body).expect("event field serialize");
    emit_program_data("PaymentTokenRevoked", &body);
}

/// FixedPriceConsignment:RecallRequested
pub fn emit_fixed_price_consignment_recall_requested(tokenId: [u8; 32], seller: [u8; 32], requestedAt: u64) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    seller.serialize(&mut body).expect("event field serialize");
    requestedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("RecallRequested", &body);
}

/// FixedPriceConsignment:SettlementNoteSet
pub fn emit_fixed_price_consignment_settlement_note_set(tokenId: [u8; 32], setter: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    setter.serialize(&mut body).expect("event field serialize");
    emit_program_data("SettlementNoteSet", &body);
}

/// FixedPriceConsignment:Unpaused
pub fn emit_fixed_price_consignment_unpaused(account: [u8; 32]) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    emit_program_data("Unpaused", &body);
}

/// KarPassport:ChallengeConcluded
pub fn emit_kar_passport_challenge_concluded(subjectId: [u8; 32], challenger: [u8; 32], bondRecipient: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    bondRecipient.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeConcluded", &body);
}

/// KarPassport:ChallengeJudged
pub fn emit_kar_passport_challenge_judged(subjectId: [u8; 32], challenger: [u8; 32], judge: [u8; 32], outcome: u8, bondRecipient: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    judge.serialize(&mut body).expect("event field serialize");
    outcome.serialize(&mut body).expect("event field serialize");
    bondRecipient.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeJudged", &body);
}

/// KarPassport:ChallengeOpened
pub fn emit_kar_passport_challenge_opened(subjectId: [u8; 32], challenger: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeOpened", &body);
}

/// KarPassport:ChallengeWithdrawn
pub fn emit_kar_passport_challenge_withdrawn(subjectId: [u8; 32], challenger: [u8; 32], bondAmount: u64, windowDuration: u64, openedAt: u64) {
    let mut body = Vec::new();
    subjectId.serialize(&mut body).expect("event field serialize");
    challenger.serialize(&mut body).expect("event field serialize");
    bondAmount.serialize(&mut body).expect("event field serialize");
    windowDuration.serialize(&mut body).expect("event field serialize");
    openedAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("ChallengeWithdrawn", &body);
}

/// KarPassport:ClaimRecorded
pub fn emit_kar_passport_claim_recorded(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimRecorded", &body);
}

/// KarPassport:ClaimWithdrawn
pub fn emit_kar_passport_claim_withdrawn(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimWithdrawn", &body);
}

/// KarPassport:CustodyLockSet
pub fn emit_kar_passport_custody_lock_set(tokenId: [u8; 32], locked: u8) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    locked.serialize(&mut body).expect("event field serialize");
    emit_program_data("CustodyLockSet", &body);
}

/// KarPassport:DisputeDepositUpdated
pub fn emit_kar_passport_dispute_deposit_updated(previousAmount: u64, newAmount: u64) {
    let mut body = Vec::new();
    previousAmount.serialize(&mut body).expect("event field serialize");
    newAmount.serialize(&mut body).expect("event field serialize");
    emit_program_data("DisputeDepositUpdated", &body);
}

/// KarPassport:PassportBridgeBurned
pub fn emit_kar_passport_passport_bridge_burned(tokenId: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    emit_program_data("PassportBridgeBurned", &body);
}

/// KarPassport:PassportBridgeMinted
pub fn emit_kar_passport_passport_bridge_minted(to: [u8; 32], tokenId: [u8; 32], uri: String) {
    let mut body = Vec::new();
    to.serialize(&mut body).expect("event field serialize");
    tokenId.serialize(&mut body).expect("event field serialize");
    uri.serialize(&mut body).expect("event field serialize");
    emit_program_data("PassportBridgeMinted", &body);
}

/// KarPassport:PassportDisputed
pub fn emit_kar_passport_passport_disputed(tokenId: [u8; 32], disputer: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    disputer.serialize(&mut body).expect("event field serialize");
    emit_program_data("PassportDisputed", &body);
}

/// KarPassport:PassportMinted
pub fn emit_kar_passport_passport_minted(to: [u8; 32], tokenId: [u8; 32], uri: String) {
    let mut body = Vec::new();
    to.serialize(&mut body).expect("event field serialize");
    tokenId.serialize(&mut body).expect("event field serialize");
    uri.serialize(&mut body).expect("event field serialize");
    emit_program_data("PassportMinted", &body);
}

/// KarPassport:PassportURIUpdated
pub fn emit_kar_passport_passport_uriupdated(tokenId: [u8; 32], newURI: String, author: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    newURI.serialize(&mut body).expect("event field serialize");
    author.serialize(&mut body).expect("event field serialize");
    emit_program_data("PassportURIUpdated", &body);
}

/// KarPassport:PassportVerified
pub fn emit_kar_passport_passport_verified(tokenId: [u8; 32], verifier: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    verifier.serialize(&mut body).expect("event field serialize");
    emit_program_data("PassportVerified", &body);
}

/// KarPassport:RecordAppended
pub fn emit_kar_passport_record_appended(tokenId: [u8; 32], author: [u8; 32], recordType: String, description: String, evidenceCID: String) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    author.serialize(&mut body).expect("event field serialize");
    recordType.serialize(&mut body).expect("event field serialize");
    description.serialize(&mut body).expect("event field serialize");
    evidenceCID.serialize(&mut body).expect("event field serialize");
    emit_program_data("RecordAppended", &body);
}

/// KarPassport:Transfer
pub fn emit_kar_passport_transfer(from: [u8; 32], to: [u8; 32], tokenId: [u8; 32]) {
    let mut body = Vec::new();
    from.serialize(&mut body).expect("event field serialize");
    to.serialize(&mut body).expect("event field serialize");
    tokenId.serialize(&mut body).expect("event field serialize");
    emit_program_data("Transfer", &body);
}

/// KarPassport:VerificationReset
pub fn emit_kar_passport_verification_reset(tokenId: [u8; 32], author: [u8; 32]) {
    let mut body = Vec::new();
    tokenId.serialize(&mut body).expect("event field serialize");
    author.serialize(&mut body).expect("event field serialize");
    emit_program_data("VerificationReset", &body);
}

/// KarPassportBridgeGateway:ONFTReceived
pub fn emit_kar_passport_bridge_gateway_onftreceived(guid: [u8; 32], srcEid: u32, toAddress: [u8; 32], tokenId: [u8; 32]) {
    let mut body = Vec::new();
    guid.serialize(&mut body).expect("event field serialize");
    srcEid.serialize(&mut body).expect("event field serialize");
    toAddress.serialize(&mut body).expect("event field serialize");
    tokenId.serialize(&mut body).expect("event field serialize");
    emit_program_data("ONFTReceived", &body);
}

/// KarPassportBridgeGateway:ONFTSent
pub fn emit_kar_passport_bridge_gateway_onftsent(guid: [u8; 32], dstEid: u32, fromAddress: [u8; 32], tokenId: [u8; 32]) {
    let mut body = Vec::new();
    guid.serialize(&mut body).expect("event field serialize");
    dstEid.serialize(&mut body).expect("event field serialize");
    fromAddress.serialize(&mut body).expect("event field serialize");
    tokenId.serialize(&mut body).expect("event field serialize");
    emit_program_data("ONFTSent", &body);
}

/// KarProPass:ProfileUpdated
pub fn emit_kar_pro_pass_profile_updated(holder: [u8; 32], category: u8, name: String, metadataURI: String) {
    let mut body = Vec::new();
    holder.serialize(&mut body).expect("event field serialize");
    category.serialize(&mut body).expect("event field serialize");
    name.serialize(&mut body).expect("event field serialize");
    metadataURI.serialize(&mut body).expect("event field serialize");
    emit_program_data("ProfileUpdated", &body);
}

/// KarProPass:ProPassBurned
pub fn emit_kar_pro_pass_pro_pass_burned(holder: [u8; 32]) {
    let mut body = Vec::new();
    holder.serialize(&mut body).expect("event field serialize");
    emit_program_data("ProPassBurned", &body);
}

/// KarProPass:ProPassMinted
pub fn emit_kar_pro_pass_pro_pass_minted(holder: [u8; 32], category: u8, name: String, metadataURI: String) {
    let mut body = Vec::new();
    holder.serialize(&mut body).expect("event field serialize");
    category.serialize(&mut body).expect("event field serialize");
    name.serialize(&mut body).expect("event field serialize");
    metadataURI.serialize(&mut body).expect("event field serialize");
    emit_program_data("ProPassMinted", &body);
}

/// KarProStaking:ClaimRecorded
pub fn emit_kar_pro_staking_claim_recorded(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimRecorded", &body);
}

/// KarProStaking:ClaimWithdrawn
pub fn emit_kar_pro_staking_claim_withdrawn(account: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    account.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("ClaimWithdrawn", &body);
}

/// KarProStaking:VerificationFeeUpdated
pub fn emit_kar_pro_staking_verification_fee_updated(verifier: [u8; 32], fee: u64) {
    let mut body = Vec::new();
    verifier.serialize(&mut body).expect("event field serialize");
    fee.serialize(&mut body).expect("event field serialize");
    emit_program_data("VerificationFeeUpdated", &body);
}

/// KarProStaking:VerifierJoined
pub fn emit_kar_pro_staking_verifier_joined(verifier: [u8; 32], asset: [u8; 32], amount: u64) {
    let mut body = Vec::new();
    verifier.serialize(&mut body).expect("event field serialize");
    asset.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    emit_program_data("VerifierJoined", &body);
}

/// KarProStaking:VerifierLeft
pub fn emit_kar_pro_staking_verifier_left(verifier: [u8; 32], amount: u64, unlockAt: u64) {
    let mut body = Vec::new();
    verifier.serialize(&mut body).expect("event field serialize");
    amount.serialize(&mut body).expect("event field serialize");
    unlockAt.serialize(&mut body).expect("event field serialize");
    emit_program_data("VerifierLeft", &body);
}

/// Stable registry for parity tests — (contract, event) pairs.
pub const REGISTRY: &[(&str, &str)] = &[
    ("AscendingConsignment", "AscendingTermsSnapshotted"),
    ("AscendingConsignment", "AuctionRulesSet"),
    ("AscendingConsignment", "BidPlaced"),
    ("AscendingConsignment", "BidRefunded"),
    ("AscendingConsignment", "ChallengeConcluded"),
    ("AscendingConsignment", "ChallengeJudged"),
    ("AscendingConsignment", "ChallengeOpened"),
    ("AscendingConsignment", "ChallengeWithdrawn"),
    ("AscendingConsignment", "ClaimRecorded"),
    ("AscendingConsignment", "ClaimWithdrawn"),
    ("AscendingConsignment", "ConsignmentClosed"),
    ("AscendingConsignment", "ConsignmentCommissionLowered"),
    ("AscendingConsignment", "ConsignmentFloorLowered"),
    ("AscendingConsignment", "ConsignmentOpened"),
    ("AscendingConsignment", "ConsignmentPriceSet"),
    ("AscendingConsignment", "ConsignmentSplitPaid"),
    ("AscendingConsignment", "FundsReleased"),
    ("AscendingConsignment", "GuardianSet"),
    ("AscendingConsignment", "MandateGranted"),
    ("AscendingConsignment", "MandateRevoked"),
    ("AscendingConsignment", "Paused"),
    ("AscendingConsignment", "PaymentTokenApproved"),
    ("AscendingConsignment", "PaymentTokenRevoked"),
    ("AscendingConsignment", "RecallRequested"),
    ("AscendingConsignment", "ReceiptConfirmed"),
    ("AscendingConsignment", "ReversalAbandoned"),
    ("AscendingConsignment", "ReversalCompleted"),
    ("AscendingConsignment", "ReversalStarted"),
    ("AscendingConsignment", "Settled"),
    ("AscendingConsignment", "Unpaused"),
    ("FixedPriceConsignment", "Bought"),
    ("FixedPriceConsignment", "ClaimRecorded"),
    ("FixedPriceConsignment", "ClaimWithdrawn"),
    ("FixedPriceConsignment", "ConsignmentClosed"),
    ("FixedPriceConsignment", "ConsignmentCommissionLowered"),
    ("FixedPriceConsignment", "ConsignmentFloorLowered"),
    ("FixedPriceConsignment", "ConsignmentOpened"),
    ("FixedPriceConsignment", "ConsignmentPriceSet"),
    ("FixedPriceConsignment", "ConsignmentSplitPaid"),
    ("FixedPriceConsignment", "CurrencyFeedSet"),
    ("FixedPriceConsignment", "ExternalPaymentConfirmed"),
    ("FixedPriceConsignment", "GuardianSet"),
    ("FixedPriceConsignment", "MandateGranted"),
    ("FixedPriceConsignment", "MandateRevoked"),
    ("FixedPriceConsignment", "NativeUsdStalenessToleranceSet"),
    ("FixedPriceConsignment", "Paused"),
    ("FixedPriceConsignment", "PaymentTokenApproved"),
    ("FixedPriceConsignment", "PaymentTokenRevoked"),
    ("FixedPriceConsignment", "RecallRequested"),
    ("FixedPriceConsignment", "SettlementNoteSet"),
    ("FixedPriceConsignment", "Unpaused"),
    ("KarPassport", "ChallengeConcluded"),
    ("KarPassport", "ChallengeJudged"),
    ("KarPassport", "ChallengeOpened"),
    ("KarPassport", "ChallengeWithdrawn"),
    ("KarPassport", "ClaimRecorded"),
    ("KarPassport", "ClaimWithdrawn"),
    ("KarPassport", "CustodyLockSet"),
    ("KarPassport", "DisputeDepositUpdated"),
    ("KarPassport", "PassportBridgeBurned"),
    ("KarPassport", "PassportBridgeMinted"),
    ("KarPassport", "PassportDisputed"),
    ("KarPassport", "PassportMinted"),
    ("KarPassport", "PassportURIUpdated"),
    ("KarPassport", "PassportVerified"),
    ("KarPassport", "RecordAppended"),
    ("KarPassport", "Transfer"),
    ("KarPassport", "VerificationReset"),
    ("KarPassportBridgeGateway", "ONFTReceived"),
    ("KarPassportBridgeGateway", "ONFTSent"),
    ("KarProPass", "ProfileUpdated"),
    ("KarProPass", "ProPassBurned"),
    ("KarProPass", "ProPassMinted"),
    ("KarProStaking", "ClaimRecorded"),
    ("KarProStaking", "ClaimWithdrawn"),
    ("KarProStaking", "VerificationFeeUpdated"),
    ("KarProStaking", "VerifierJoined"),
    ("KarProStaking", "VerifierLeft"),
];

