import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outPath = path.join(root, "lib/contracts/abis.generated.ts");

const contracts = [
  {
    exportName: "KarPassport",
    artifactPath: "artifacts/contracts/KarPassport.sol/KarPassport.json",
  },
  {
    exportName: "KarProPass",
    artifactPath: "artifacts/contracts/KarProPass.sol/KarProPass.json",
  },
  {
    exportName: "KarProStaking",
    artifactPath:
      "artifacts/contracts/KarProStaking.sol/KarProStaking.json",
  },
  {
    exportName: "MarketplaceEscrow",
    artifactPath:
      "artifacts/contracts/MarketplaceEscrow.sol/MarketplaceEscrow.json",
  },
  {
    exportName: "AuctionEscrow",
    artifactPath:
      "artifacts/contracts/AuctionEscrow.sol/AuctionEscrow.json",
  },
  {
    exportName: "FixedPriceConsignment",
    artifactPath:
      "artifacts/contracts/FixedPriceConsignment.sol/FixedPriceConsignment.json",
  },
  {
    exportName: "AscendingConsignment",
    artifactPath:
      "artifacts/contracts/AscendingConsignment.sol/AscendingConsignment.json",
  },
  {
    exportName: "KarPassportBridgeGateway",
    artifactPath:
      "artifacts/contracts/KarPassportBridgeGateway.sol/KarPassportBridgeGateway.json",
  },
];

const lines = [
  "// Auto-generated by scripts/export-abis.mjs — do not edit manually",
  "",
];

for (const { exportName, artifactPath } of contracts) {
  const fullPath = path.join(root, artifactPath);
  if (!fs.existsSync(fullPath)) {
    throw new Error(
      `Missing artifact: ${artifactPath}. Run "pnpm hardhat compile" first.`,
    );
  }

  const { abi } = JSON.parse(fs.readFileSync(fullPath, "utf8"));
  if (!Array.isArray(abi)) {
    throw new Error(`Artifact ${artifactPath} does not contain an abi array.`);
  }

  lines.push(
    `export const ${exportName}Abi = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  );
}

for (const { exportName } of contracts) {
  lines.push(`export type ${exportName}Abi = typeof ${exportName}Abi;`);
}

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");

console.log(`Wrote ${outPath}`);
